name: Java CI with Gradle

on:
  [ pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create application.yml
        run: |
          touch C:\Users\s2008\Consolation-Server\src\main\resources\application.yml
          echo ${{ secrets.APPLICATION_YML }} >> application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test