name: Java CI with Gradle

on:
  pull_request:
    branches: [ feature/s3, develop ]

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Create application.yml
        run: |
          touch ./src/main/resources/application.yml
          echo "${{ secrets.SECRET_APPLICATION_YML }}" >> ./src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

